# Generated by Django 2.0 on 2020-03-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20200328_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='timeStamp',
            new_name='datetime',
        ),
    ]
