# Generated by Django 2.0 on 2020-04-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imbd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
