# Generated by Django 2.0 on 2020-04-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200404_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
