# Generated by Django 2.0 on 2020-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200417_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
    ]
