# Generated by Django 2.0 on 2020-06-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_recommendmatrix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendMatrix',
        ),
    ]
